project.name=intyg

artifact.name=intygstjanst
artifact.version=4.2.0.8

sbom.aggregation.module=app
sbom.aggregation.path=app

git.url=https://github.com/sklintyg/intygstjanst.git
git.branch=main

builder.image=app-builder-image
builder.image.tag=21.0.6

runtime.image=springboot-base
runtime.image.tag=21.0.2

dependencies.common.version=4.3.0.+

dependencies.common.version.resolved=4.3.0.1

build.args=build spotlessCheck testAggregateTestReport
sonarqube.args=