---

- name: Drop any existing mysql database for 'test' environment
  mysql_db: name={{ database_name }} state=absent
  when: environment_name == "test"

- name: Create mysql database
  mysql_db: name={{ database_name }} state=present
    
- name: Create mysql user
  mysql_user: name={{ database_username }} password={{ database_username }} priv=*.*:ALL state=present
        
