apiVersion: v1
stringData:
  NTJP_WS_CERTIFICATE_PASSWORD: password
  NTJP_WS_KEY_MANAGER_PASSWORD: password
  NTJP_WS_TRUSTSTORE_PASSWORD: password
kind: Secret
metadata:
  name: intygstjanst-devtest-secret-envvar
type: Opaque
