apiVersion: v1
data:
  ACTIVEMQ_BROKER_URL: failover:(tcp://ind-sint-activemq1.ind1.sth.basefarm.net:61616,tcp://ind-sint-activemq2.ind1.sth.basefarm.net:61616)?jms.nonBlockingRedelivery=true&jms.redeliveryPolicy.useExponentialBackOff=true&jms.redeliveryPolicy.backOffMultiplier=2&jms.redeliveryPolicy.maximumRedeliveries=30&jms.redeliveryPolicy.maximumRedeliveryDelay=3600000&jms.redeliveryPolicy.initialRedeliveryDelay=60000
  ACTIVEMQ_DESTINATION_QUEUE_NAME: statistik.utlatande.queue
  NTJP_WS_CERTIFICATE_FILE: ${certificate.folder}/qa.minaintyg.sjunet.org.p12
  NTJP_WS_CERTIFICATE_TYPE: PKCS12
  NTJP_WS_TRUSTSTORE_FILE: ${certificate.folder}/truststore-ntjp.jks
  NTJP_WS_TRUSTSTORE_TYPE: JKS
  REDIS_SERVICE_HOST: ind-sint-redis1.ind1.sth.basefarm.net;ind-sint-redis2.ind1.sth.basefarm.net;ind-sint-redis3.ind1.sth.basefarm.net
  REDIS_SERVICE_PORT: 26379;26379;26379
  REFDATA_URL: file://localhost/opt/intygstjanst/env/refdata-1.0.0.66.jar
  RESOURCES_FOLDER: 'classpath:'
  TSBAS_SEND_CERTIFICATE_TO_RECIPIENT_REGISTERCERTIFICATE_VERSION: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2019-04-05T15:03:02Z
  name: intygstjanst-configmap-envvar
  namespace: sintyg
  resourceVersion: "72873624"
  selfLink: /api/v1/namespaces/sintyg/configmaps/intygstjanst-configmap-envvar
  uid: e8702a09-57b3-11e9-935a-005056a1387d
