apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: intygstjanst
  name: intygstjanst
spec:
  output:
    to:
      kind: ImageStreamTag
      name: intygstjanst:latest
  resources: {}
  source:
    git:
      ref: feature/openshift
      uri: https://github.com/sklintyg/intygstjanst.git
    contextDir: /
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: MAVEN_MIRROR_URL
        value: http://nexus-route-intygstjanster-test.192.168.99.100.nip.io/repository/maven-public/
      - name: commonVersion
        value: 3.6.0.+
      - name: infraVersion
        value: 3.6.0.+
      - name: buildVersion
        value: 3.6.0.0-OPENSHIFT
      from:
        kind: "ImageStreamTag"
        name: "intyg-s2i:latest"
      forcePull: true

