---
# This playbook deploys Intygstjansten 

- hosts: intygstjanst-tomcat
  sudo: yes 
  vars: 
    # repo - values: snapshots or releases
    repo: releases
    version: 2.5.0-b15
    config_version: master

  roles:
    - intygstjanst
