CREATE TABLE original_certificate (
  ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
  RECEIVED TIMESTAMP NOT NULL,
  DOCUMENT LONGVARBINARY NOT NULL
);

CREATE TABLE certificate (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  CERTIFICATE_TYPE VARCHAR(255) NOT NULL,
  CIVIC_REGISTRATION_NUMBER VARCHAR(255) NOT NULL,
  CARE_UNIT_NAME VARCHAR(255) NOT NULL,
  SIGNING_DOCTOR_NAME VARCHAR(255) NOT NULL,
  SIGNED_DATE TIMESTAMP NOT NULL,
  VALID_FROM_DATE VARCHAR(10) NOT NULL,
  VALID_TO_DATE VARCHAR(10) NOT NULL,
  DELETED TINYINT DEFAULT NULL,
  DOCUMENT LONGVARBINARY NOT NULL
);
