CREATE TABLE CERTIFICATE (
  ID VARCHAR(255) NOT NULL PRIMARY KEY,
  CERTIFICATE_TYPE VARCHAR(255) NOT NULL,
  CIVIC_REGISTRATION_NUMBER VARCHAR(255) NOT NULL,
  CARE_UNIT_NAME VARCHAR(255) NOT NULL,
  CARE_UNIT_ID VARCHAR(255) NOT NULL,
  SIGNING_DOCTOR_NAME VARCHAR(255) NOT NULL,
  SIGNED_DATE TIMESTAMP NOT NULL,
  VALID_FROM_DATE VARCHAR(10) NOT NULL,
  VALID_TO_DATE VARCHAR(10) NOT NULL,
  DELETED TINYINT DEFAULT NULL,
  DOCUMENT BLOB NOT NULL
);

CREATE TABLE ORIGINAL_CERTIFICATE (
  ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
  RECEIVED TIMESTAMP NOT NULL,
  DOCUMENT BLOB NOT NULL,
  CERTIFICATE_ID VARCHAR(255),
  FOREIGN KEY (CERTIFICATE_ID)
      REFERENCES CERTIFICATE(ID)
);

CREATE TABLE CERTIFICATE_STATE (
  CERTIFICATE_ID varchar(255) NOT NULL,
  TARGET varchar(255) NOT NULL,
  STATE varchar(255) NOT NULL,
  TIMESTAMP datetime NOT NULL,
  FOREIGN KEY (CERTIFICATE_ID) REFERENCES CERTIFICATE(ID)
);
