CREATE TABLE `certificate` (
  `ID` varchar(255) NOT NULL,
  `CERTIFICATE_TYPE` varchar(255) NOT NULL,
  `CIVIC_REGISTRATION_NUMBER` varchar(255) NOT NULL,
  `CARE_UNIT_NAME` varchar(255) NOT NULL,
  `CARE_UNIT_ID` VARCHAR(255) NOT NULL,
  `SIGNING_DOCTOR_NAME` varchar(255) NOT NULL,
  `SIGNED_DATE` datetime NOT NULL,
  `VALID_FROM_DATE` varchar(10) NOT NULL,
  `VALID_TO_DATE` varchar(10) NOT NULL,
  `DELETED` tinyint(1) DEFAULT NULL,
  `WIRETAPPED` tinyint(1) DEFAULT 0,
  `DOCUMENT` blob NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_CERTIFICATE_CIVIC_REGISTRATION_NUMBER` (`CIVIC_REGISTRATION_NUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `original_certificate` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RECEIVED` datetime NOT NULL,
  `DOCUMENT` blob NOT NULL,
  `CERTIFICATE_ID` varchar(255), 
  PRIMARY KEY (`ID`),
  FOREIGN KEY (CERTIFICATE_ID)
      REFERENCES certificate(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
