---

- name: stop tomcat
  service: name={{ tomcat_service }} state=stopped pattern=org.apache.catalina.startup.Bootstrap

- name: remove old version of liquibase-runner
  file: state=absent
      path=/tmp/intygstjanst-liquibase-runner.jar

- name: Download war
  get_url: url=http://repository-callistasoftware.forge.cloudbees.com/release/se/inera/intyg/intygstjanst/intygstjanst-liquibase-runner/{{ version }}/intygstjanst-liquibase-runner-{{ version }}-jar-with-dependencies.jar
      dest=/tmp/intygstjanst-liquibase-runner.jar

- name: run liquibase update
  command: java -jar /tmp/intygstjanst-liquibase-runner.jar --changeLogFile="changelog/changelog.xml" --contexts=none update chdir=/opt/inera/liquibase

- name: remove old version of unpacked war
  file: state=absent
      path={{ webapps_folder }}/inera-certificate

- name: remove old version of war
  file: state=absent
      path={{ webapps_folder }}/inera-certificate.war

- name: Download war
  get_url: url=http://repository-callistasoftware.forge.cloudbees.com/release/se/inera/intyg/intygstjanst/intygstjanst-web/{{ version }}/intygstjanst-web-{{ version }}.war
           dest={{ webapps_folder }}/inera-certificate.war

- name: Create version file
  template: src=version.txt.j2 dest={{ webapps_folder }}/version.txt

- name: update configuration
  git: repo={{ config_repo }}
    dest={{ config_folder }}
    version=master

- name: start tomcat
  service: name={{ tomcat_service }} state=started pattern=org.apache.catalina.startup.Bootstrap
