---
# file: roles/intygstjanst/tasks/main.yml

- name: stop tomcat
  service: name={{ tomcat_service }} state=stopped pattern={{ tomcat_service }}

- name: create release directory
  file: path={{ releases_folder }} state=directory

- name: download intygstjanst-liquibase-runner-{{ version }}.zip
  get_url: url=https://build-inera.nordicmedtest.se/nexus/content/repositories/{{ repo }}/se/inera/intyg/intygstjanst/intygstjanst-liquibase-runner/{{ version }}/intygstjanst-liquibase-runner-{{ version }}.zip
           dest={{ releases_folder }}/intygstjanst-liquibase-runner-{{ version }}.zip
  when: deploy_from_repo

- name: copy intygstjanst-liquibase-runner-{{ version }}.zip
  copy: src={{ inventory_dir }}/../tools/liquibase-runner/target/intygstjanst-liquibase-runner.zip dest={{ releases_folder }}/intygstjanst-liquibase-runner-{{ version }}.zip
  when: not deploy_from_repo

- name: Unzip liquibase-runner-{{ version }}.zip
  command: unzip -od {{ releases_folder }} {{ releases_folder }}/intygstjanst-liquibase-runner-{{ version }}.zip
  args:
    creates: "{{ releases_folder }}/intygstjanst-liquibase-runner-{{ version }}/bin/liquibase-runner"

- name: run liquibase update
  command: "{{ releases_folder }}/intygstjanst-liquibase-runner-{{ version }}/bin/intygstjanst-liquibase-runner --url={{ database_url }} --username={{ database_username }} --password={{ database_password }} update"
  args:
      chdir: "{{ releases_folder }}/intygstjanst-liquibase-runner-{{ version }}"
  environment:
      JAVA_HOME: "{{ java_home }}"

- name: download intygstjanst-web-{{ version }}.war
  get_url: url=https://build-inera.nordicmedtest.se/nexus/content/repositories/{{ repo }}/se/inera/intyg/intygstjanst/intygstjanst-web/{{ version }}/intygstjanst-web-{{ version }}.war
           dest={{ releases_folder }}/intygstjanst-web-{{ version }}.war
           timeout=120
  when: deploy_from_repo

- name: copy intygstjanst-web-{{ version }}.war
  copy: src={{ inventory_dir }}/../web/target/intygstjanst.war dest={{ releases_folder }}/intygstjanst-web-{{ version }}.war
  when: not deploy_from_repo

- name: remove old version of unpacked war
  file: state=absent
      path={{ webapps_folder }}/inera-certificate

- name: remove old version of war
  file: state=absent
      path={{ webapps_folder }}/inera-certificate.war

- name: deploy intygstjanst-web-{{ version }}.war as inera-certificate.war
  command: cp {{ releases_folder }}/intygstjanst-web-{{ version }}.war {{ webapps_folder }}/inera-certificate.war

- name: create version file
  template: src=version.txt.j2 dest={{ webapps_folder }}/version.txt

- name: pull configuration repo to get new branches
  command: chdir={{ config_folder }} git pull origin

- name: update configuration to {{ config_version }}
  git: repo={{ config_repository }}
       dest={{ config_folder }}
       version={{ config_version }}

- name: start tomcat
  service: name={{ tomcat_service }} state=started pattern={{ tomcat_service }}
